# Generated by Django 4.2.2 on 2023-06-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_productosminimos_fecha_de_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosminimos',
            name='estatus',
            field=models.CharField(default='Disponible o No disponible', max_length=300, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='productosminimos',
            name='fecha_de_registro',
            field=models.CharField(default='mm/dd/yy', max_length=8, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='productosminimos',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
