# Generated by Django 4.2.2 on 2023-06-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_alter_productosminimos_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productosminimos',
            name='estatus',
            field=models.CharField(default='Disponible / No disponible', max_length=300, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='productosminimos',
            name='nombre',
            field=models.CharField(default='Nombre del producto', max_length=300, verbose_name='Nombre'),
        ),
    ]
